---
title: "ESM 204 HW 4"
author: "Maggie Hammond, Savana Gonzalez, and Ali Martin"
date: "5/16/2022"
output: 
  html_document:
    code_folding: hide
    theme: yeti
    toc: yes
    toc_depth: 5
    toc_float: yes
    collapsed: yes
    smooth_scroll: yes
    number_sections: no
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)

library(tidyverse)
library(here)
library(janitor)
library(equatiomatic)
library(broom)
library(ggpubr)
library(kableExtra)
library(FinancialMath)
library(lifecontingencies)
library(readr)
library(cowplot)


```


```{r}
damage <- read_csv(here("damages.csv"))

warming <- read_csv(here("warming.csv"))
```



## Question 1: Estimate a quadratic damage function


```{r}
# Question 1 work
damage$warming2 <- damage$warming^2

qm_damages <- lm(damages ~ 0 +  warming + warming2 - 1, data = damage)

extract_eq(model = qm_damages, 
           use_coefs = TRUE,
           coef_digits = 4)

damage_model <- function(x){-1059530137756.23*x + 19409275730643.3*x^2}

ggplot(data = damage, aes(x = warming, y = damages)) +
  stat_function(fun = damage_model, color = "purple") +
  geom_point(size = 2) +
  labs(x = "Warming (C)",
       y = "Total Damages ($)") +
  theme_minimal()


```

## Question 2

```{r}
warming$warming_norm_damage <- damage_model(warming$warming_baseline)

warming$warming_pulse_damage <- damage_model(warming$warming_pulse)

warming$warming_damage_diff <- warming$warming_pulse_damage - warming$warming_norm_damage

warming$warming_damage_diff_per_CO2 <- warming$warming_damage_diff/35000000000


## Graph 1:  Damages over time without pulse
p1 <- ggplot(data = warming, aes(x = year, y = warming_norm_damage)) +
  geom_line()+ labs(x = "Year", y = "Damages from Climate Change ($)", title = "Annual Damages to Temperature Under  \n Normal Conditions")

## Graph 2: Damages Over time with the pulse
p2 <- ggplot(data = warming, aes(x = year, y = warming_pulse_damage)) +
  geom_line()+ labs(x = "Year", y = "Damages from Climate Change ($)", title = "Annual Damages to Temperature With  \n CO2 Pulse")

## Graph 3: Difference in Damages over time from the pulse 
p3 <- ggplot(data = warming, aes(x = year, y = warming_damage_diff)) +
  geom_line()+ labs(x = "Year", y = "Difference in Damages from Climate Change ($)", title = "Annual Difference in Damages to Temperature \n With CO2 Pulse")

## Graph 4: Difference in Damages over time from pulse per ton of Co2
p4 <- ggplot(data = warming, aes(x = year, y = warming_damage_diff)) +
  geom_line()+ labs(x = "Year", y = "Difference Damages from Climate Change ($)", title = "Annual Difference in Damages with Pulse per Ton of CO2")


```

## Question #3

```{r}
NPV(cf0 = warming$warming_damage_diff_per_CO2[1], cf = (warming$warming_damage_diff_per_CO2), times = c(1:79), i = .01)
```


```{r}
warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_1 = warming_damage_diff_per_CO2 / (1 + .01)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_2 = warming_damage_diff_per_CO2 / (1 + .02)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_3 = warming_damage_diff_per_CO2 / (1 + .03)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_4 = warming_damage_diff_per_CO2 / (1 + .04)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_5 = warming_damage_diff_per_CO2 / (1 + .05)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_6 = warming_damage_diff_per_CO2 / (1 + .06)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_7 = warming_damage_diff_per_CO2 / (1 + .07)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_8 = warming_damage_diff_per_CO2 / (1 + .08)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_9 = warming_damage_diff_per_CO2 / (1 + .09)^(...1-1))

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_10 = warming_damage_diff_per_CO2 / (1 + .10)^(...1-1))



pv_1 <- sum(warming$present_value_1[1:79])
pv_2 <- sum(warming$present_value_2[1:79])
pv_3 <- sum(warming$present_value_3[1:79])
pv_4 <- sum(warming$present_value_4[1:79])
pv_5 <- sum(warming$present_value_5[1:79])
pv_6 <- sum(warming$present_value_6[1:79])
pv_7 <- sum(warming$present_value_7[1:79])
pv_8 <- sum(warming$present_value_8[1:79])
pv_9 <- sum(warming$present_value_9[1:79])
pv_10 <- sum(warming$present_value_10[1:79])


scc <- c(pv_1, pv_2, pv_3, pv_4, pv_5, pv_6, pv_7, pv_8, pv_9, pv_10)
discount_rate <- c(.01, .02, .03, .04, .05, .06, .07, .08, .09, .10)

scc_rate <- data.frame(scc, discount_rate)

ggplot(data = scc_rate, aes(y = scc, x = discount_rate)) +
  geom_point() +
  labs(x = "Discount Rate",
       y = "Social Cost of Carbon",
       title = "SCC and Discount Rate") +
  theme_minimal()
```

## Question 4

```{r}

# from Ramsey's Rule, we get a discount rate of 2.1% 

warming <- warming %>% 
  mutate(warming_damage_diff_per_CO2, present_value_ramsey = warming_damage_diff_per_CO2 / ((1 + .021)^(...1-1)))

pv_ramsey <- sum(warming$present_value_ramsey[1:79])

scc_ramsey <- pv_ramsey
discount_ramsey <- .021

ramsey_rate <- data.frame(scc_ramsey, discount_ramsey)

caption <- "Figure X. the gold dot represents the Ramsey Rate discount rate and Social Cost of Carbon calculation"
ggplot() +
  geom_point(data = scc_rate, 
             aes(x = discount_rate, y = scc), 
             color = "green") +
  geom_point(data = ramsey_rate, 
             aes(x = discount_ramsey, y = scc_ramsey), 
             color = "gold") +
    labs(x = "Discount Rate",
       y = "Social Cost of Carbon",
       title = "SCC and Discount Rate",
       caption = str_wrap(caption)) +
  theme_minimal()

```


## Question 5

```{r}
# Policy A - BAU

warming <- warming %>% 
  mutate(warming_norm_damage, policy_A_opt1 = (warming_norm_damage / (1 + .02)^(...1-1)))

policy_A_opt1_final <- sum(warming$policy_A_opt1[1:79])*.5

warming$warming_1.5_damage <- damage_model(warming$warming_baseline*1.5)

warming <- warming %>% 
  mutate(warming_1.5_damage, policy_A_opt2 = ((warming_1.5_damage) / (1 + .02)^(...1-1)))


policy_A_opt2_final <- sum(warming$policy_A_opt2[1:79])*.5

policy_A <- policy_A_opt1_final + policy_A_opt2_final

```

```{r}
# Policy B - Immediate & Strong Action

warming <- warming %>% 
  mutate(warming_norm_damage, pv_option_b = warming_norm_damage / (1 + .02)^(...1-1))

warming <- warming %>%
  mutate(warming_norm_damage, steady = warming_norm_damage[30] / (1 + .02)^(...1-1))


present_value <- (warming$pv_option_b[1:29])
baseline_damage <- (warming$warming_norm_damage[1:29])

pv_policy_b <- data.frame(baseline_damage, present_value)

df_1 <- data.frame(year = warming$year[1:29],
                   baseline_damages = pv_policy_b$baseline_damage[1:29],
                   present_value_b = pv_policy_b$present_value[1:29])

df_2 <- data.frame(year = warming$year[30:79],
                   baseline_damages = warming$warming_norm_damage[30:79],
                   present_value_b = warming$steady[30:79])

policy_B_final_df <- rbind(df_1, df_2)

policy_b_sum_pv <- sum(policy_B_final_df$present_value_b[1:79])
```



```{r}
### Compare Policy A and Policy B
# policy A has no implementation cost, policy B has x implementation cost

policy_b_model <- function(x){policy_b_sum_pv+x}

policy_a_model <- function(x){policy_A}

ggplot() +
  scale_color_manual(values = c('orange', 'purple2')) +
  stat_function(fun = policy_b_model, color = 'orange') +
  stat_function(fun = policy_a_model, color = 'purple2') +
  ylim(0, 6e+15) +
  xlim(0, 5e+15) +
  labs(x = "Implenetation Cost ($)",
       y = "Total Cost",
       title = "Comparing Policy A and B Costs",
       caption = "Figure X. Policy A (purple) indicates there is no implementation cost. Policy B (orange) shows there is an implementation cost of X") +
  theme_minimal()

dif_costs_model <- function(x){policy_A - (policy_b_sum_pv+x)}
policy_equal <- uniroot(dif_costs_model, c(1e15, 2.5e15))

```

Congress should implement Policy B

## Question 6

If society is more risk averse, they would most likely choose Policy B because the future damages are lower than for Policy A, and Policy B is less risky than Policy A. 